# Generated by Django 5.2.7 on 2025-11-11 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_tbl_subcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_adminregistration',
            new_name='tbl_admin',
        ),
    ]
