# Generated by Django 5.2.7 on 2025-11-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicetype_name', models.CharField(max_length=50)),
            ],
        ),
    ]
