# Generated by Django 5.2.7 on 2025-12-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Technician', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_technicianleave',
        ),
    ]
