# Generated by Django 5.2.7 on 2025-12-12 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Technician', '0002_delete_tbl_technicianleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_technicianleave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_fromdate', models.DateField()),
                ('leave_todate', models.DateField()),
                ('leave_reason', models.CharField(max_length=200)),
                ('leave_status', models.IntegerField(default=0)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_technician')),
            ],
        ),
    ]
