# Generated by Django 5.2.7 on 2025-12-11 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_product',
        ),
    ]
