# Generated by Django 5.2.7 on 2025-11-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0007_tbl_brand'),
        ('Guest', '0010_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician_name', models.CharField(max_length=50)),
                ('technician_email', models.CharField(max_length=50)),
                ('technician_contact', models.CharField(max_length=20)),
                ('technician_address', models.CharField(max_length=100)),
                ('technician_photo', models.FileField(upload_to='Assets/User/Photo')),
                ('technician_proof', models.FileField(upload_to='Assets/User/Photo')),
                ('technician_status', models.IntegerField(default=0)),
                ('technician_password', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
