# Generated by Django 5.2.7 on 2025-11-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0008_tbl_servicetype'),
        ('Guest', '0010_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_serviceproviderstype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
            ],
        ),
    ]
