# Generated by Django 5.2.7 on 2025-11-11 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0006_rename_tbl_adminregistration_tbl_admin'),
        ('Guest', '0002_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_address', models.CharField(max_length=100)),
                ('user_photo', models.FileField(upload_to='Assets/User/Photo')),
                ('user_proof', models.FileField(upload_to='Assets/User/Photo')),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
