# Generated by Django 5.2.7 on 2025-11-19 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_company',
        ),
    ]
