# Generated by Django 5.2.7 on 2025-11-19 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_brand'),
        ('Guest', '0005_delete_tbl_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_email', models.CharField(max_length=50)),
                ('company_contact', models.CharField(max_length=20)),
                ('company_address', models.CharField(max_length=100)),
                ('company_logo', models.FileField(upload_to='Assets/User/Photo')),
                ('company_proof', models.FileField(upload_to='Assets/User/Photo')),
                ('company_status', models.CharField(max_length=100)),
                ('company_password', models.CharField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_brand')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
