# Generated by Django 5.2.7 on 2025-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_tbl_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_company',
            name='company_status',
            field=models.IntegerField(default=0),
        ),
    ]
