# Generated by Django 5.2.7 on 2025-11-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_tbl_brand'),
        ('Guest', '0007_alter_tbl_company_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_serviceprovider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceprovider_name', models.CharField(max_length=50)),
                ('serviceprovider_email', models.CharField(max_length=50)),
                ('serviceprovider_contact', models.CharField(max_length=50)),
                ('serviceprovider_address', models.CharField(max_length=100)),
                ('serviceprovider_photo', models.FileField(upload_to='Assets/User/Photo')),
                ('serviceprovider_proof', models.FileField(upload_to='Assets/User/Photo')),
                ('seviceprovider_password', models.CharField(max_length=30)),
                ('serviceprovider_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
