# Generated by Django 5.2.7 on 2025-11-19 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0008_tbl_serviceprovider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_serviceprovider',
        ),
    ]
