# Generated by Django 5.2.7 on 2025-12-11 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_servicetype'),
        ('Guest', '0010_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=50)),
                ('shop_email', models.CharField(max_length=100)),
                ('shop_contact', models.CharField(max_length=25)),
                ('shop_address', models.CharField(max_length=200)),
                ('shop_photo', models.FileField(upload_to='Assets/User/Photo')),
                ('shop_proof', models.FileField(upload_to='Assets/User/Photo')),
                ('shop_password', models.CharField(max_length=30)),
                ('shop_status', models.IntegerField(default=0)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
