# Generated by Django 5.2.7 on 2026-04-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_tbl_user_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_range', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_serviceprovider',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_experience'),
        ),
    ]
