# Generated by Django 5.2.7 on 2025-11-24 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Guest', '0010_tbl_serviceprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_companyservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyservice_content', models.CharField(max_length=200)),
                ('companyservice_date', models.DateTimeField()),
                ('companyservice_status', models.IntegerField(default=0)),
                ('companyservice_amount', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_technician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
