# Generated by Django 5.2.7 on 2025-11-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_companyservice',
            name='companyservice_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tbl_companyservice',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_technician'),
        ),
    ]
