# Generated by Django 5.2.7 on 2025-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_tbl_companyservice_companyservice_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_companyservice',
            name='companyservice_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
