# Generated by Django 5.2.7 on 2025-11-27 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_tbl_servicerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_servicerequest',
        ),
    ]
