# Generated by Django 5.2.7 on 2025-11-27 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_tbl_servicetype'),
        ('Guest', '0010_tbl_serviceprovider'),
        ('User', '0005_delete_tbl_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_servicerequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicerequest_content', models.CharField(max_length=200)),
                ('servicerequest_date', models.DateTimeField(auto_now_add=True)),
                ('servicerequest_amount', models.IntegerField(null=True)),
                ('servicerequest_status', models.IntegerField(default=0)),
                ('servicerequest_todate', models.DateField()),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('servicetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_servicetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
