# Generated by Django 5.2.7 on 2025-12-01 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_tbl_serviceprovider'),
        ('User', '0006_tbl_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=200)),
                ('complaint_content', models.CharField(max_length=1000)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
