# Generated by Django 5.2.7 on 2025-12-02 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_tbl_complaint_technician_alter_tbl_complaint_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
