# Generated by Django 5.2.7 on 2025-12-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
