# Generated by Django 5.2.7 on 2025-12-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_tbl_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.IntegerField(default=0),
        ),
    ]
