# Generated by Django 5.2.7 on 2025-12-04 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0014_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_complaint',
            name='servicerequest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_servicerequest'),
        ),
    ]
