# Generated by Django 5.2.7 on 2025-12-11 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_tbl_complaint_servicerequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
