# Generated by Django 5.2.7 on 2025-12-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0019_tbl_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_amount',
            field=models.FloatField(null=True),
        ),
    ]
