# Generated by Django 5.2.7 on 2026-01-01 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Guest', '0011_tbl_shop'),
        ('Shop', '0004_tbl_stock'),
        ('User', '0023_delete_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=200)),
                ('complaint_content', models.CharField(max_length=1000)),
                ('complaint_date', models.DateField(auto_now_add=True)),
                ('complaint_reply', models.CharField(max_length=500)),
                ('complaint_status', models.IntegerField(default=0)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_company')),
                ('companyservice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_companyservice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
                ('serviceprovider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_serviceprovider')),
                ('servicerequest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_servicerequest')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_shop')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Company.tbl_technician')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
