# Generated by Django 5.2.7 on 2026-01-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0024_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
