# Generated by Django 5.2.7 on 2026-01-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0030_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='product',
        ),
    ]
