# Generated by Django 5.2.7 on 2026-01-08 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0031_remove_tbl_complaint_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
