# Generated by Django 5.2.7 on 2026-01-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0034_tbl_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
