# Generated by Django 5.2.7 on 2026-01-08 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_shop'),
        ('User', '0035_delete_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_date', models.DateField(auto_now_add=True)),
                ('rating_content', models.CharField(max_length=1000)),
                ('rating_value', models.CharField(max_length=100)),
                ('companyservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_companyservice')),
                ('servicerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_servicerequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
