# Generated by Django 5.2.7 on 2026-01-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_tbl_stock'),
        ('User', '0036_tbl_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_rating',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_cart'),
        ),
        migrations.AddField(
            model_name='tbl_rating',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product'),
        ),
    ]
