# Generated by Django 5.2.7 on 2026-01-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0037_tbl_rating_cart_tbl_rating_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_rating',
        ),
    ]
