# Generated by Django 5.2.7 on 2026-01-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_shop'),
        ('Shop', '0004_tbl_stock'),
        ('User', '0038_delete_tbl_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_datetime', models.DateField(auto_now_add=True)),
                ('user_review', models.CharField(max_length=1000)),
                ('rating_data', models.IntegerField(default=0)),
                ('companyservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_companyservice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product')),
                ('servicerequest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.tbl_servicerequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
