# Generated by Django 5.2.7 on 2026-01-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0039_tbl_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_rating',
            old_name='rating_datetime',
            new_name='datetime',
        ),
    ]
