# Generated by Django 5.2.7 on 2026-02-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0040_rename_rating_datetime_tbl_rating_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_servicerequest',
            name='servicerequest_remark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
