# Generated by Django 5.2.7 on 2026-02-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0041_tbl_servicerequest_servicerequest_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_companyservice',
            name='companyservice_remark',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
