# Generated by Django 5.2.7 on 2026-02-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0042_tbl_companyservice_companyservice_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_servicerequest',
            name='servicerequest_reject',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
