# Generated by Django 5.2.7 on 2026-03-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0043_tbl_servicerequest_servicerequest_reject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_companyservice',
            name='companyservice_date',
            field=models.DateTimeField(),
        ),
    ]
