# Generated by Django 5.2.7 on 2026-03-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0044_alter_tbl_companyservice_companyservice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_servicerequest',
            name='servicerequest_date',
            field=models.DateTimeField(),
        ),
    ]
