# Generated by Django 5.2.7 on 2026-03-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0045_alter_tbl_servicerequest_servicerequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
