# Generated by Django 5.2.7 on 2026-03-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0047_alter_tbl_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
